---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu-22.04
    pre_build_image: true
    image: dokken/ubuntu-22.04
    groups:
      - python3
      - prometheus
      - alertmanager
      - grafana
      - exporters
      - web
    privileged: true
    cgroup_parent: docker.slice
    command: /lib/systemd/systemd
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
  inventory:
    links:
      group_vars: ../../group_vars/
      host_vars: host_vars/
  env:
    ANSIBLE_ROLES_PATH: "../../roles"
verifier:
  name: testinfra
