---
- name: Prepare
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Install packages
      ansible.builtin.package:
        name:
          - openssh-server
          - openssh-client
        state: present
        update_cache: true

    - name: Create dir
      ansible.builtin.file:
        path: "/run/sshd"
        state: directory
        mode: 0755
