---
- name: Setup HTTP server
  hosts: web
  roles:
    - caddy_ansible.caddy_ansible
  pre_tasks:
    - name: Ensure webdirs exists
      ansible.builtin.file:
        mode: '0755'
        path: "{{ item }}"
        state: directory
      loop:
        - /var/www/demo
        - /var/www/demo/img
    - name: Ensure portal site exists
      ansible.builtin.copy:
        mode: '0644'
        src: index.html
        dest: /var/www/demo/index.html
